pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
const C=new Map(),D=new Set();let N=1;
const $=s=>document.querySelector(s),BRL=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
function num(s){s=String(s||"").replace(/[^0-9.,-]/g,"");if(s.includes(".")&&s.includes(","))s=s.replace(/\./g,"").replace(",",".");else s=s.replace(",",".");return Math.abs(parseFloat(s)||0)}
function status(t,k="i"){let e=$("#status");e.className="mt-4 rounded-xl border px-3 py-2 text-sm "+(k==="ok"?"border-emerald-500/30 bg-emerald-500/10 text-emerald-200":k==="err"?"border-red-500/30 bg-red-500/10 text-red-200":"border-slate-700 bg-slate-900 text-slate-300");e.textContent=t}
function key(f){return f.name+"::"+f.size+"::"+f.lastModified}
function add(file=null,manual=false){let id=N++,f=$("#tpl").content.cloneNode(true),e=f.querySelector(".conta");e.dataset.id=id;e.querySelector(".titulo").textContent=file?file.name:"Conta manual #"+id;e.querySelector(".icone").textContent=manual?"✍️":"⏳";e.querySelector(".st").textContent=manual?"Preencha os valores":"Preparando leitura...";$("#contas").appendChild(f);e=document.querySelector('[data-id="'+id+'"]');C.set(id,{id,file,buf:null,e,manual});e.querySelector(".remover").onclick=()=>{let c=C.get(id);if(c&&c.file)D.delete(key(c.file));C.delete(id);e.remove();calc()};e.querySelectorAll(".fatura,.creditos,.kwh,.ref").forEach(x=>x.oninput=calc);e.querySelector(".retry").onclick=()=>retry(id);calc();return id}
async function files(fs){let a=[...fs],fresh=a.filter(f=>{let k=key(f);if(D.has(k))return false;D.add(k);return true});if(!fresh.length){status("Esses PDFs já foram adicionados.");return}status("Lendo "+fresh.length+" conta(s)...");let pass=$("#senhaPadrao").value;for(let f of fresh){let id=add(f);let c=C.get(id);c.buf=await f.arrayBuffer();await load(id,pass)}$("#files").value="";status("Processamento concluído. Confira os valores extraídos.","ok")}
async function retry(id){let c=C.get(id),p=c.e.querySelector(".senha").value;if(!p)return;c.e.querySelector(".senha").value="";await load(id,p)}
async function allPass(){let p=$("#senhaPadrao").value;if(!p){status("Digite a senha das contas.","err");return}let a=[...C.values()].filter(c=>c.file&&c.buf&&!c.manual&&!c.e.querySelector(".senhaBox").classList.contains("hidden"));if(!a.length){status("Não há contas aguardando senha.");return}for(let c of a)await load(c.id,p);status("Senha aplicada nas contas protegidas.")}
async function load(id,p=""){let c=C.get(id),e=c.e;e.querySelector(".icone").textContent="⏳";e.querySelector(".st").textContent="Lendo PDF...";try{let pdf=await pdfjsLib.getDocument({data:new Uint8Array(c.buf.slice(0)),password:p||undefined}).promise,lines=await text(pdf),d=parse(lines);fill(e,d);e.querySelector(".senhaBox").classList.add("hidden");e.querySelector(".icone").textContent="✅";e.querySelector(".st").textContent=d.creditos?"PDF lido. Confira os valores.":"PDF lido; créditos não identificados. Preencha manualmente.";calc()}catch(x){let pw=x&&((x.name==="PasswordException")||x.code===1||x.code===2||/password/i.test(String(x.message||"")));if(pw){e.querySelector(".senhaBox").classList.remove("hidden");e.querySelector(".icone").textContent="🔒";e.querySelector(".st").textContent=p?"A senha geral não abriu este PDF. Tente outra só aqui.":"PDF protegido por senha."}else{e.querySelector(".icone").textContent="⚠️";e.querySelector(".st").textContent="Não foi possível ler automaticamente. Preencha manualmente."}}}
async function text(pdf){let out=[];for(let p=1;p<=pdf.numPages;p++){let pg=await pdf.getPage(p),ct=await pg.getTextContent(),rows=new Map;for(let it of ct.items){let y=Math.round(it.transform[5]);if(!rows.has(y))rows.set(y,[]);rows.get(y).push({x:it.transform[4],t:it.str})}[...rows.keys()].sort((a,b)=>b-a).forEach(y=>{let l=rows.get(y).sort((a,b)=>a.x-b.x).map(i=>i.t).join(" ").trim();if(l)out.push(l)})}return out}
function parse(lines){let full=lines.join("\n"),fatura=0,creditos=0,kwh=0,ref="";
for(let l of lines){let m=l.match(/TOTAL\s*A\s*PAGAR[^0-9]*R?\$?\s*([0-9.]+,[0-9]{2})/i)||l.match(/(?:TOTAL|Valor do Documento)\s*[: ]+R?\$?\s*([0-9.]+,[0-9]{2})/i);if(m){fatura=num(m[1]);if(fatura)break}}
if(!fatura)for(let l of lines)if(/TOTAL|PAGAR|DOCUMENTO|VENCIMENTO/i.test(l)){let v=[...l.matchAll(/R\$\s*([0-9.]+,[0-9]{2})/gi)].map(m=>num(m[1]));if(v.length){fatura=v[v.length-1];break}}
for(let l of lines.filter(l=>/ENERGIA\s+(?:ATV|ATIVA).*INJ|ADIC(?:IONAL)?\.?\s+BAND.*COMP|COMPENSA/i.test(l))){let m=l.match(/kWh\s+[0-9.,]+\s+[0-9.,]+-?\s+([0-9.,]+)\s*-/i);if(m){creditos+=num(m[1]);continue}let n=[...l.matchAll(/([0-9.]+,[0-9]{2})\s*-/g)].map(m=>num(m[1])).filter(Boolean);if(n.length)creditos+=Math.max(...n)}
let m=full.match(/Energia\s+Injetada[^\n]*?([0-9.]+(?:,[0-9]+)?)\s*kWh/i);if(m)kwh=num(m[1]);m=full.match(/(?:MÊS\/ANO|REFER[ÊE]NCIA)[^0-9]{0,30}(0[1-9]|1[0-2])\/(20\d{2})/i)||full.match(/\b(0[1-9]|1[0-2])\/(20\d{2})\b/);if(m)ref=m[1]+"/"+m[2];return{fatura,creditos,kwh,ref}}
function fill(e,d){if(d.fatura)e.querySelector(".fatura").value=d.fatura.toFixed(2);if(d.creditos)e.querySelector(".creditos").value=d.creditos.toFixed(2);if(d.kwh)e.querySelector(".kwh").value=d.kwh;if(d.ref)e.querySelector(".ref").value=d.ref}
function calc(){let tf=0,tc=0,refs=[];for(let c of C.values()){let e=c.e,f=+e.querySelector(".fatura").value||0,cr=+e.querySelector(".creditos").value||0,s=cr*.8,ec=cr*.2;tf+=f;tc+=cr;e.querySelector(".vSolar").textContent=BRL(s);e.querySelector(".vTotal").textContent=BRL(f+s);e.querySelector(".vEco").textContent=BRL(ec);let r=e.querySelector(".ref").value.trim();if(r)refs.push(r)}let solar=tc*.8,eco=tc*.2;$("#totFatura").textContent=BRL(tf);$("#totCred").textContent=BRL(tc);$("#totSolar").textContent=BRL(solar);$("#totFinal").textContent=BRL(tf+solar);$("#ecoMes").textContent=BRL(eco);$("#ecoAno").textContent=BRL(eco*12);$("#qtd").textContent=C.size?(C.size===1?"1 conta/unidade adicionada":C.size+" contas/unidades adicionadas"):"Nenhuma conta adicionada";let u=[...new Set(refs)],m=$("#meses");if(u.length>1){m.textContent="Atenção: contas de meses diferentes ("+u.join(", ")+").";m.classList.remove("hidden")}else m.classList.add("hidden")}
$("#files").onchange=e=>files(e.target.files);$("#manual").onclick=()=>add(null,true);$("#aplicarSenha").onclick=allPass;$("#mostrarSenha").onclick=()=>{let i=$("#senhaPadrao"),b=$("#mostrarSenha");i.type=i.type==="password"?"text":"password";b.textContent=i.type==="password"?"Mostrar senha":"Ocultar senha"};$("#limpar").onclick=()=>{C.clear();D.clear();$("#contas").innerHTML="";$("#files").value="";$("#status").classList.add("hidden");calc()};$("#senhaPadrao").onkeydown=e=>{if(e.key==="Enter")allPass()};calc();